<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    0 => '',
    1 => '',
    2 => '',
    3 => '',
    4 => '',
    5 => '',
    6 => '',
    7 => '',
    8 => '',
    9 => '',
    10 => '',
    11 => '',
    12 => '',
    13 => '',
    14 => '',
    15 => '',
    16 => '',
    17 => '',
    'Create At' => 'Добавлено',
    'Growth' => 'Рост',
    'ID' => '',
    'Result' => 'Результат',
    'Result Percent' => 'Результата в процентах',
    'Result Standart' => 'Стандартный результат',
    'Sex' => 'Пол',
    'Update At' => 'Обновлено',
    'Updated' => 'Обновить',
    'User ID' => 'Пользователь',
    'Are you sure you want to delete this item?' => '@@@@',
    'Create Examination' => 'Создать запись',
    'Delete' => 'Удалить',
    'Examinations' => 'Оценка состояния',
    'Reset' => 'Сбросить',
    'Save' => 'Сохранить',
    'Search' => 'Найти',
    'The requested page does not exist.' => 'Страница не создана',
    'Update' => 'Обновить',
    'Update Examination: {nameAttribute}' => 'Обновить',
    'Member since' => 'Участник с ',
    'Profile' => 'Профиль',
    'Sign out' => 'Выйти',
    'You have' => 'У вас есть ',
    'tasks' => 'записей',
    'green  tasks' => 'В зеленой зоне',
    'yellow  tasks' => 'В желтой зоне',
    'red  tasks' => 'В красной зоне',
    'Exam Category' => 'Категория',
    'green'  => 'Зеленая зона',
    'yellow'  => 'Желтая зона',
    'red'  => 'Красная зона',


];
