<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'A password will be generated automatically if not provided' => '',
    'Account details' => '',
    'Account settings' => '',
    'Are you sure you want to block this user?' => '',
    'Are you sure you want to confirm this user?' => '',
    'Are you sure you want to delete this user?' => '',
    'Are you sure you want to switch to this user for the rest of this Session?' => '',
    'Are you sure you want to unblock this user?' => '',
    'Are you sure?' => '',
    'Are you sure? There is no going back' => '',
    'Assignments' => '',
    'Become this user' => '',
    'Block' => '',
    'Block status' => '',
    'Blocked at {0, date, MMMM dd, YYYY HH:mm}' => '',
    'Change your avatar at Gravatar.com' => '',
    'Confirm' => '',
    'Confirmation' => '',
    'Confirmation status' => '',
    'Confirmed' => '',
    'Confirmed at {0, date, MMMM dd, YYYY HH:mm}' => '',
    'Connect' => '',
    'Create' => '',
    'Create a user account' => '',
    'Credentials will be sent to the user by email' => '',
    'Delete' => '',
    'Delete account' => '',
    'Disconnect' => '',
    'Generate and send new password to user' => '',
    'Information' => '',
    'It will be deleted forever' => '',
    'Manage users' => '',
    'Networks' => '',
    'Never' => '',
    'New permission' => '',
    'New role' => '',
    'New rule' => '',
    'New user' => '',
    'Not blocked' => '',
    'Once you delete your account, there is no going back' => '',
    'Permissions' => '',
    'Please be certain' => '',
    'Profile details' => '',
    'Profile settings' => '',
    'Registration IP' => '',
    'Registration time' => '',
    'Roles' => '',
    'Rules' => '',
    'Save' => '',
    'Unblock' => '',
    'Unconfirmed' => '',
    'Update' => '',
    'Update user account' => '',
    'Users' => '',
    'You can assign multiple roles or permissions to user by using the form below' => '',
    'You can connect multiple accounts to be able to log in using them' => '',
    '{0, date, MMMM dd, YYYY HH:mm}' => '',
];
